
export const uniqueUsernames = [
    { username: 'user1' },
    { username: 'user2' },
    { username: 'user3' },
    { username: 'user4' },
    { username: 'user5' },
    { username: 'user6' },
    { username: 'user7' },
    { username: 'user8' },
    { username: 'user9' },
    { username: 'user10' },
    { username: 'user11' },
    { username: 'user12' },
    { username: 'user13' },
    { username: 'user14' },
    { username: 'user15' },
    { username: 'user16' },
    { username: 'user17' },
    { username: 'user18' },
    { username: 'user19' },
    { username: 'user20' },
    { username: 'user21' },
    { username: 'user22' },
    { username: 'user23' },
    { username: 'user24' },
    { username: 'user25' },
    { username: 'user26' },
    { username: 'user27' },
    { username: 'user28' },
    { username: 'user29' },
    { username: 'user30' },
] as const;
  
export const roles = [
  { roleName: 'Role1', active: true },
  { roleName: 'Role2', active: false },
  { roleName: 'Role3', active: true },
  { roleName: 'Role4', active: false },
  { roleName: 'Role5', active: true },
  { roleName: 'Role6', active: false },
  { roleName: 'Role7', active: true },
  { roleName: 'Role8', active: false },
  { roleName: 'Role9', active: true },
  { roleName: 'Role10', active: false },
  { roleName: 'Role11', active: true },
  { roleName: 'Role12', active: false },
  { roleName: 'Role13', active: true },
  { roleName: 'Role14', active: false },
  { roleName: 'Role15', active: true },
  { roleName: 'Role16', active: false },
  { roleName: 'Role17', active: true },
  { roleName: 'Role18', active: false },
  { roleName: 'Role19', active: true },
  { roleName: 'Role20', active: false },
  { roleName: 'Role21', active: true },
  { roleName: 'Role22', active: false },
  { roleName: 'Role23', active: true },
  { roleName: 'Role24', active: false },
  { roleName: 'Role25', active: true },
  { roleName: 'Role26', active: false },
  { roleName: 'Role27', active: true },
  { roleName: 'Role28', active: false },
  { roleName: 'Role29', active: true },
  { roleName: 'Role30', active: false },
] as const;

