


import HeaderMain from '@/components/Header/HeaderMain';
import './globals.css'
import { Metadata } from 'next';
import { Inter } from 'next/font/google'
import { RecoilRoot } from 'recoil';
import LayoutComponent from '@/components/PageComponent';

const inter = Inter({ subsets: ['latin'] });


export const metadata: Metadata = {
	title: "Employee Management | Turkish",
	description:
		"Key features of the Employee Management System include comprehensive employee information management, leave and attendance tracking, payroll processing, performance evaluation, recruitment and onboarding, employee self-service portals, and robust reporting and analytics capabilities. These features collectively work to streamline HR operations, reduce manual paperwork, and enhance overall HR efficiency.Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`inter.className bg-gray-100`}>
       
        <LayoutComponent>
          {children}
        </LayoutComponent>
       
      </body>
    </html>
  )
}
